// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(LogContext))]
    partial class LogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Domain.Entities.Advice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceEntryId");

                    b.ToTable("Advices");
                });

            modelBuilder.Entity("Domain.Entities.EntryChunk", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntryId", "Number");

                    b.ToTable("EntryChunks");
                });

            modelBuilder.Entity("Domain.Entities.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("Domain.Entities.Advice", b =>
                {
                    b.HasOne("Domain.Entities.LogEntry", "SourceEntry")
                        .WithMany("Advices")
                        .HasForeignKey("SourceEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceEntry");
                });

            modelBuilder.Entity("Domain.Entities.EntryChunk", b =>
                {
                    b.HasOne("Domain.Entities.LogEntry", "Entry")
                        .WithMany("Chunks")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Domain.Entities.LogEntry", b =>
                {
                    b.Navigation("Advices");

                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
